#!/usr/bin/env python3
"""
Convert a WAV file to a C header with raw PCM data.

Usage:
    python3 wav_to_header.py input.wav [output.h]

The WAV file will be resampled to 48kHz stereo 16-bit PCM to match
the USB audio headset format (192 bytes per 1ms frame).

If no output file is specified, writes to 'audio_clip.h' in the
parent src/ directory.

Requirements:
    pip install scipy numpy   (for resampling)
    OR provide a WAV file already in 48kHz stereo 16-bit format.
"""

import sys
import struct
import wave
import os

def read_wav(filename):
    """Read WAV file and return (samples, sample_rate, channels, sample_width)."""
    with wave.open(filename, 'rb') as wf:
        channels = wf.getnchannels()
        sample_width = wf.getsampwidth()
        sample_rate = wf.getframerate()
        n_frames = wf.getnframes()
        raw = wf.readframes(n_frames)

    if sample_width == 2:
        fmt = f'<{n_frames * channels}h'
        samples = list(struct.unpack(fmt, raw))
    elif sample_width == 1:
        # 8-bit unsigned → 16-bit signed
        samples = [(b - 128) * 256 for b in raw]
    else:
        print(f"Unsupported sample width: {sample_width} bytes")
        sys.exit(1)

    return samples, sample_rate, channels, 2  # always output 16-bit


def mono_to_stereo(samples):
    """Duplicate mono samples to stereo."""
    stereo = []
    for s in samples:
        stereo.append(s)
        stereo.append(s)
    return stereo


def resample_simple(samples, channels, src_rate, dst_rate):
    """Simple nearest-neighbor resampling (no dependency needed)."""
    n_frames = len(samples) // channels
    ratio = src_rate / dst_rate
    new_n_frames = int(n_frames / ratio)
    result = []
    for i in range(new_n_frames):
        src_idx = int(i * ratio)
        if src_idx >= n_frames:
            src_idx = n_frames - 1
        for ch in range(channels):
            result.append(samples[src_idx * channels + ch])
    return result


def write_header(filename, samples, sample_rate, channels):
    """Write C header with PCM data."""
    n_frames = len(samples) // channels
    total_bytes = len(samples) * 2  # 16-bit
    duration_ms = (n_frames * 1000) // sample_rate
    frame_size = channels * 2  # bytes per sample frame
    usb_frame_bytes = 48 * channels * 2  # 48 samples per 1ms USB frame

    with open(filename, 'w') as f:
        f.write("/* Auto-generated by wav_to_header.py — do not edit */\n")
        f.write(f"/* Source: {sample_rate}Hz, {channels}ch, 16-bit PCM */\n")
        f.write(f"/* Duration: {duration_ms}ms, {n_frames} frames, {total_bytes} bytes */\n")
        f.write(f"/* USB frames (1ms each): {n_frames // 48} */\n\n")
        f.write("#ifndef AUDIO_CLIP_H\n")
        f.write("#define AUDIO_CLIP_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define AUDIO_CLIP_SAMPLE_RATE  {sample_rate}\n")
        f.write(f"#define AUDIO_CLIP_CHANNELS     {channels}\n")
        f.write(f"#define AUDIO_CLIP_NUM_FRAMES   {n_frames}\n")
        f.write(f"#define AUDIO_CLIP_USB_FRAMES   {n_frames // 48}\n")
        f.write(f"#define AUDIO_CLIP_FRAME_BYTES  {usb_frame_bytes}\n\n")
        f.write(f"static const int16_t audio_clip_data[{len(samples)}] = {{\n")

        # Write 8 samples per line
        for i in range(0, len(samples), 8):
            chunk = samples[i:i+8]
            line = ", ".join(f"{s:6d}" for s in chunk)
            comma = "," if i + 8 < len(samples) else ""
            f.write(f"\t{line}{comma}\n")

        f.write("};\n\n")
        f.write("#endif /* AUDIO_CLIP_H */\n")

    print(f"Generated {filename}:")
    print(f"  {sample_rate}Hz, {channels}ch, 16-bit PCM")
    print(f"  {n_frames} sample frames ({duration_ms}ms)")
    print(f"  {total_bytes} bytes ({total_bytes // 1024}KB)")
    print(f"  {n_frames // 48} USB frames (1ms each)")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 wav_to_header.py input.wav [output.h]")
        print("\nThe WAV will be converted to 48kHz stereo 16-bit PCM.")
        print("Keep clips short (1-3 seconds) to fit in embedded flash.")
        sys.exit(1)

    input_file = sys.argv[1]
    if len(sys.argv) >= 3:
        output_file = sys.argv[2]
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_file = os.path.join(script_dir, '..', 'src', 'audio_clip.h')

    samples, src_rate, channels, _ = read_wav(input_file)

    # Convert mono to stereo
    if channels == 1:
        print(f"Converting mono to stereo...")
        samples = mono_to_stereo(samples)
        channels = 2

    # Resample to 48kHz if needed
    if src_rate != 48000:
        print(f"Resampling {src_rate}Hz → 48000Hz...")
        samples = resample_simple(samples, channels, src_rate, 48000)
        src_rate = 48000

    # Clamp to 16-bit range
    samples = [max(-32768, min(32767, s)) for s in samples]

    # Truncate to whole USB frames (48 stereo samples = 1ms)
    usb_frame_samples = 48 * channels
    total = len(samples)
    total = (total // usb_frame_samples) * usb_frame_samples
    samples = samples[:total]

    write_header(output_file, samples, src_rate, channels)


if __name__ == '__main__':
    main()
